language: node_js
node_js:
  - node
deploy:
  provider: heroku
  app: scoopsahoy
  api_key:
    secure: xE3sI9P78kVh8j2QPTs0J5GniWZlPZaSYYKCR4xVAfxvCI02JIfWQ/v1pnfxXcMCYMx3EGOqm/BNAsIqvqfZNXQMZk00qPHfrq0/eKC8GIHODrpZ/gRuMGiVCfrtQCUXactSObzkLaJ5h+BpT7RCjykTDL/f5XRqYiDZHBSCNC710Ub6Xe1OydDkadiy6i7jasGMQBtC4LnE+aBeIpefqFCoi5inyedSJoc2a6fU3YqZrphWuUaVlk1DK9R8lrkXjrcSTkJK3bWOsxf1V2QSaAZuzcEnLDiRmzLEilENe5GiFjLuMD1MG2nAvMNFxAsUZxy74zVnA7z4kkPF/P1+KJIGotYztktmajcxn99CZ1gyY6jMcIT3E/MuupxyIMXHa2ugx0cVAkB727H4EFspxYavdqdJPjN36rch22+Nrt8OibHxJXAq5l6A1+Fx0ToCubzDOCAYJA1QjtWIQL3oCND0JEEXKSdLGs+i2hnhGV3yUoLaF/CUdL+mCnPSrbfU5yG+m5BAwqTfF4QDG5KLKUyi5GD1xfPUwUEeDb4ITr8OUfIpp9k8nI3C4/N5GO4p7IX4IV8Ya8XXyNaTXpCZyotH8hiTjobaYGFddCP7gJjbucLunxZFBNMfzC1zFveiK3Jz54Hi3y8ByQ82T2fETQA3DqFREOFgU/8EwTEXUZg=
